name: skawa_components_example
version: 1.2.0

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  skawa_components:
    path: "../skawa_components/skawa_components"
  skawa_material_components:
    path: "../skawa_components/skawa_material_components"
  sass_builder: ^2.1.2

dev_dependencies:
  build_config: ^0.4.1+1
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
